version: "3.9"
services:
  acinoset:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.acinoset.cui
    image: denden047/acinoset_cui
    volumes:
      - ./src:/workplace
      - ./data:/data
    working_dir: /workplace
    command: /bin/bash -c "./all_flick.sh"